name = "ai-img-engine"
main = "src/index.js"
compatibility_date = "2024-02-24"
workers_dev = true

[[routes]]
pattern = "ai.tomaskrcal.cloud"
zone_name = "tomaskrcal.cloud"
custom_domain = true

[ai]
binding = "AI"
