name = "ai-img-engine"
main = "src/index.js"
compatibility_date = "2024-02-24"
workers_dev = false
account_id = "" # INSERT VALUE
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[[routes]]
pattern = "" # INSERT VALUE
zone_name = "" # INSERT VALUE
custom_domain = true

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "" # INSERT VALUE
database_id = "" # INSERT VALUE

[[r2_buckets]]
binding = "S3"
preview_bucket_name = "" # INSERT VALUE
bucket_name = "" # INSERT VALUE

[vars]
OPEN_AI_KEY = ""
