name = "ai-img-engine"
main = "src/index.js"
compatibility_date = "2024-02-24"
workers_dev = true
account_id = "" # INSERT VALUE
compatibility_flags = [ "nodejs_compat" ]

[[routes]]
pattern = "ai.tomaskrcal.cloud"
zone_name = "tomaskrcal.cloud"
custom_domain = true

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "" # INSERT VALUE
database_id = "" # INSERT VALUE

[[r2_buckets]]
binding = "S3"
preview_bucket_name = "img-engine"
bucket_name = "img-engine"
