name = "ai-img-engine"
main = "src/index.js"
compatibility_date = "2024-02-24"
workers_dev = true
account_id = "d3451b99dacd0d2c4bc99281390107fa"
compatibility_flags = [ "nodejs_compat" ]

[[routes]]
pattern = "ai.tomaskrcal.cloud"
zone_name = "tomaskrcal.cloud"
custom_domain = true

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "prod-img-engine"
database_id = "22339285-0d15-4735-82ec-71be88ccb0d5"

[[r2_buckets]]
binding = "S3"
preview_bucket_name = "img-engine"
bucket_name = "img-engine"
