name: Lint Code Base

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: UI Eslint
        run: |
          cd ui
          npm install
          npm run lint
